[dnbd3-proxy-mode] Continuously try to switch to local server
We might spontaneously switch away from the local server if it is
overloaded, and then never switch back because the thresold to the
remote server is too low. Nudge the block device to localhost every now
and then.

diff --git a/core/modules/dnbd3-proxy-mode/data/opt/openslx/scripts/systemd-dnbd3_local_stage4 b/core/modules/dnbd3-proxy-mode/data/opt/openslx/scripts/systemd-dnbd3_local_stage4
--- a/core/modules/dnbd3-proxy-mode/data/opt/openslx/scripts/systemd-dnbd3_local_stage4
+++ b/core/modules/dnbd3-proxy-mode/data/opt/openslx/scripts/systemd-dnbd3_local_stage4
@@ -4,12 +4,14 @@
 if [ -d "/mnt/dnbd3" ] && [ -b /dev/dnbd0 ] \
 		&& [ "$( cat /sys/block/dnbd0/net/rid )" -gt 0 ]; then
 	DNBD3_PORT=5003
+	addr="127.0.0.1:$DNBD3_PORT"
 	# give it some time to start
-	usleep 250000
+	usleep 128000
 	if ! grep -q -F 127.0.0.1 /sys/block/dnbd0/net/alt_servers; then
 		# add the server
-		if ! dnbd3-client -A "127.0.0.1:$DNBD3_PORT" -d /dev/dnbd0; then
+		if ! dnbd3-client -A "$addr" -d /dev/dnbd0; then
 			echo "WARN: Cannot add localhost to dnbd0" >&2
+			 grep -q -F 127.0.0.1 /sys/block/dnbd0/net/alt_servers || exit 1
 		fi
 	fi
 	# Call this repeatedly - this will keep resetting the RTT values to
@@ -18,12 +20,25 @@ if [ -d "/mnt/dnbd3" ] && [ -b /dev/dnbd0 ] \
 	# local dnbd3 proxy replies slower than some upstream server on the
 	# network, which is not that unlikely if the data is not cached
 	# locally yet.
-	for i in 1 2 4 8 16 32 64; do
-		dnbd3-client -s "127.0.0.1:$DNBD3_PORT" -d /dev/dnbd0 &> /dev/null
+	# /sys/block/dnbd0/net/cur_server_addr
+	for i in 1 2 4 8 16 32 64 128; do
+		dnbd3-client -s "$addr" -d /dev/dnbd0 &> /dev/null
 		usleep ${i}00000 # tenths of a second
 	done
-	# One last time without swallowing any errors
-	dnbd3-client -s "127.0.0.1:$DNBD3_PORT" -d /dev/dnbd0
+	# Bump towards localhost every now and then, since a hiccup might've switched us away
+	fails=0
+	while sleep 21; do
+		if ! dnbd3-client -s "$addr" -d /dev/dnbd0 &> /dev/null; then
+			fails=$(( fails + 1 ))
+			if [ "$fails" -gt 4 ]; then
+				dnbd3-client -s "$addr" -d /dev/dnbd0 # Don't swallow output here
+				echo "Cannot switch to local dnbd3-server, bailing out" >&2
+				exit 1
+			fi
+		else
+			fails=0
+		fi
+	done
 fi
 
 exit 0
