[init/kexec/] More advanced network setup via KCL, could skip DHCP
If enough information if provided via KCL, we can skip the initial DHCP
request in stage 3.1. Currently we require IP address, subnet mask and
DNS server to skip DHCP. If we extend the boot server to supply a
fallback/default DNS server, we could even do without DNS which would
work in almost all cases.

kexec-reboot has been extended to make use of this feature, but can be
extended even more to provide up to date values from the current system
configuration. Currently, some of the values it provides to the new
kernel will be cached values from stage 3.1.
kexec-reboot also honors the ipxe menu id from the KCL if given, to
properly download the matching menu entry, which will take updates to
the entry into account (e.g. changed URLs to kernel/init).

diff --git a/core/modules/kexec-reboot/data/opt/openslx/scripts/systemd-kexec_load b/core/modules/kexec-reboot/data/opt/openslx/scripts/systemd-kexec_load
--- a/core/modules/kexec-reboot/data/opt/openslx/scripts/systemd-kexec_load
+++ b/core/modules/kexec-reboot/data/opt/openslx/scripts/systemd-kexec_load
@@ -1,4 +1,4 @@
-#!/bin/ash
+#!/bin/bash
 
 kexec=$(which kexec 2>/dev/null)
 if [ -z "$kexec" ]; then
@@ -8,22 +8,93 @@ fi
 
 . /opt/openslx/bin/slx-tools
 
+perror() {
+	echo "$*" >&2
+	exit 1
+}
+
+# Download <base> <relative_or_absolute>
+dl_prefix() {
+	local url
+	if regex_imatch "$2" 'https?:'; then
+		url="$2"
+	else
+		url="$1/${2#/}"
+	fi
+	download_retry "$url"
+}
+
 kexec_load() {
 	. /opt/openslx/config
-	local DIR="$(mktemp -d)"
-
-	for FILE in kernel initramfs-stage31; do
-		if ! download_retry "http://${SLX_KCL_SERVERS}/${SLX_BASE_PATH}/${FILE}" > "${DIR}/${FILE}" ; then
-			echo "Failed to download ${FILE}."
-			exit 1
-		fi
+	local serverip="${SLX_KCL_SERVERS%% *}"
+	local base="http://${serverip}"
+	local tempdir oldKcl ipxeId
+	local newKernel newInitRd newKcl
+	tempdir="$(mktemp -d)"
+	newKernel="${tempdir}/kernel"
+	newInitRd="${tempdir}/initrd"
+	read -r oldKcl < /proc/cmdline
+	newKcl="$oldKcl" # Fallback
+	ipxeId=
+	for opts in ${oldKcl}; do
+		case "${opts}" in
+			slx.ipxe.id=*)
+				ipxeId="${opts#slx.ipxe.id=}"
+				;;
+		esac
 	done
-	if download_retry "http://${SLX_KCL_SERVERS}/tftp/bwlp.cpio" > "${DIR}/bwlp.cpio"; then
-		cat "${DIR}/initramfs-stage31" "${DIR}/bwlp.cpio" > "${DIR}/initramfs-tmp"
-		mv -f -- "${DIR}/initramfs-tmp" "${DIR}/initramfs-stage31"
+
+	if [ -n "$ipxeId" ]; then
+		local ok=
+		if ! download_retry "${base}/boot/ipxe?type=bash&entryid=$ipxeId&uuid=$(cat /etc/system-uuid)" > "${tempdir}/bootentry"; then
+			echo "Could not download iPXE menu entry, falling back..."
+		else
+			local ip="$( ip addr show dev br0 | awk '{ if ($1 == "inet") { print $2; exit 0 }}' )"
+			local gateway="$( ip route show dev br0 | awk '{ if ($1 == "default") {print $3; exit 0 }}' )"
+			local dns="${SLX_DNS// /,}"
+			local hostname="${SLX_HOSTNAME}"
+			local domain="${SLX_NET_DOMAIN}"
+			local dnssl="${SLX_NET_SEARCH// /,}"
+			local mac="${SLX_PXE_MAC}"
+			local ntpsrv="${SLX_NTP_SERVER// /,}"
+			[ -z "$mac" ] && mac="$( ip addr show dev br0 | awk '{ if ($1 == "link/ether") { print $2; exit 0 }}' )"
+			. "${tempdir}/bootentry"
+			if [ -z "$kernel" ]; then
+				echo "iPXE boot entry is missing kernel, falling back..."
+			elif [ -z "$initrd" ]; then
+				echo "iPXE boot entry is missing initRd, falling back..."
+			else
+				# OK-ish, download files
+				dl_prefix "${base}" "${kernel}" > "$newKernel" \
+					|| perror "Error downloading new kernel $kernel"
+				for file in "${initrd[@]}"; do
+					dl_prefix "${base}" "${file}" >> "$newInitRd" \
+						|| perror "Could not download initrd $file"
+				done
+				if [ -n "$kcl" ]; then
+					newKcl="${kcl} slx.ipxe.id=$ipxeId"
+					echo "New KCL is $newKcl"
+				fi
+				ok=true
+			fi
+		fi
+		[ -z "$ok" ] && ipxeId=
 	fi
-	if ! kexec -l "${DIR}/kernel" --initrd "${DIR}/initramfs-stage31" --reuse-cmdline; then
-		echo "Failed to load kernel/initrd from ${DIR}"
+	if [ -z "$ipxeId" ]; then
+		echo "No iPXE menu id, guessing file names..."
+		download_retry "${base}/${SLX_BASE_PATH}/kernel" > "$newKernel" \
+			|| perror "Failed to download new kernel."
+		download_retry "${base}/${SLX_BASE_PATH}/initramfs-stage31" > "$newInitRd" \
+			|| perror "Failed to download new initramfs."
+		# Logo is not critical
+		download_retry "${base}/tftp/bwlp.cpio" > "$tempdir/logo" \
+			&& cat "$tempdir/logo" >> "$newInitRd"
+		newKcl="$( cat /proc/cmdline )"
+		# TODO patch all the ipv4.* vars if they exist
+	fi
+
+	if ! kexec -l "${newKernel}" --initrd "${newInitRd}" --command-line="${newKcl}"; then
+		echo "Failed to load kernel/initrd from ${tempdir}"
 		exit 1
 	fi
 }
diff --git a/core/rootfs/rootfs-stage31/data/inc/udhcpc-trigger b/core/rootfs/rootfs-stage31/data/inc/udhcpc-trigger
--- a/core/rootfs/rootfs-stage31/data/inc/udhcpc-trigger
+++ b/core/rootfs/rootfs-stage31/data/inc/udhcpc-trigger
@@ -1,11 +1,25 @@
 #!/bin/ash
 
-exec >> /run/stdout
 exec 2>> /run/stderr
 set -x
 
 if [ "x$1" != "xbound" -a "x$1" != "xrenew" ] || [ "x$interface" != "xbr0" ] || [ -z "$ip" ]; then
+	echo "Ignoring DHCP hook '$1' for interface '$interface' -> '$ip'"
 	exit 0
+fi
+
+if [ "$ip" != "${ip#*/}" ]; then # CIDR
+	cidr="$ip"
+	ip="${ip%/*}"
+elif [ -n "$mask" ]; then
+	cidr="$ip/$mask"
+else
+	if [ -z "$subnet" ]; then
+		echo "$1 event with missing subnet mask"
+		exit 1
+	fi
+	# Non-CIDR + mask
+	cidr="$ip/$( ipcalc -s -p "$ip" "$subnet" | sed 's/.*=//' )"
 fi
 
 # If we already got an IP from KCL, see if it differs, and remove first if so
@@ -21,14 +35,14 @@ if [ -s "/run/firstip" ]; then
 		ip route del default 2>/dev/null
 		rm -f -- "/run/firstgw"
 		ip addr del "${OLD}" dev "${interface}" 2>/dev/null
-		ip addr add "${ip}/$(ipcalc -s -p "${ip}" "${subnet}" | sed s/.*=//)" dev "${interface}"
+		ip addr add "${cidr}" dev "${interface}"
 	fi
 else
 	#...no address configured yet, just add...
 	echo "..adding ${ip}.."
-	ip addr add "${ip}/$(ipcalc -s -p "${ip}" "${subnet}" | sed s/.*=//)" dev "${interface}"
+	ip addr add "${cidr}" dev "${interface}"
 fi
-echo -n "$ip" > "/run/firstip"
+printf "%s" "$ip" > "/run/firstip"
 
 # Same procedure for default gateway
 if [ -n "${router}" ]; then
@@ -42,7 +56,7 @@ if [ -n "${router}" ]; then
 	else
 		ip route add default via "$router"
 	fi
-	echo -n "$router" > "/run/firstgw"
+	printf "%s" "$router" > "/run/firstgw"
 fi
 
 rm -f -- "/etc/resolv.conf"
@@ -56,7 +70,7 @@ fi
 for serv in $dns; do
 	echo "nameserver $serv" >> "/etc/resolv.conf"
 done
-if [ -z "$domain" ]; then
+if [ -z "$domain" ] && [ -n "$dns" ]; then
 	# try to get domain via reverse lookup if empty
 	echo "..trying to get domain via DNS, as DHCP didn't supply one.."
 	fqdn=$(timeout -t 3 nslookup "$ip" | grep -E "^Address +[0-9]+: +$ip " | head -n 1 | awk '{print $4}')
@@ -92,7 +106,7 @@ done
 if [ -z "$hostname" ]; then
 	# as with domain, if there's no hostname, try to get via DNS
 	echo "..trying to get hostname via DNS, as DHCP didn't supply one.."
-	[ -z "$fqdn" ] && fqdn=$(timeout -t 3 nslookup "$ip" | grep -E "^Address +[0-9]+: +$ip " | head -n 1 | awk '{print $4}')
+	[ -z "$fqdn" ] && [ -n "$dns" ] && fqdn=$(timeout -t 3 nslookup "$ip" | grep -E "^Address +[0-9]+: +$ip " | head -n 1 | awk '{print $4}')
 	hostname="${fqdn%%.*}"
 elif [ -n "$domain" ]; then
 	fqdn="${hostname}.${domain}"
@@ -111,3 +125,4 @@ if [ -n "$hostname" ]; then
 	echo "SLX_HOSTNAME='$hostname'" >> "/run/config"
 fi
 
+exit 0
