merge with latest dev version (tm-scripts commit f5a59daf8d70a9027118292cd40b18c221897408)

diff --git a/core/modules/debug/data/opt/openslx/bin/debug_report b/core/modules/debug/data/opt/openslx/bin/debug_report
--- a/core/modules/debug/data/opt/openslx/bin/debug_report
+++ b/core/modules/debug/data/opt/openslx/bin/debug_report
@@ -1,4 +1,5 @@
-#!/bin/ash
+#!/bin/bash
+# bash because of {,} expansion
 
 TOOLS="
 	journalctl
@@ -8,6 +9,7 @@ TOOLS="
 	lsusb
 	lsmod
 	mount
+	dmidecode
 "
 
 URL="http://132.230.8.113/error_report.php"
@@ -30,37 +32,49 @@ if [ ! -d /tmp/debug-report ]; then
 	exit 1
 fi
 
-cd /tmp/debug-report
+if ! cd /tmp/debug-report; then
+	echo "Cannot go to /tmp/debug-report"
+	exit 1
+fi
 
 cat > err-desc <<HEREEND
 
 # Bitte hier kurz eine passende Fehlerbeschreibung eingeben, anschließend
-# Strg+O, ENTER, und Strg+X drücken.
+# Strg+O, ENTER, Strg+X, ENTER drücken.
 HEREEND
 
 nano -w err-desc
+
+if ! grep -vqE '(^$)|(^# )' err-desc; then
+	echo "Fehlerberichterstattung aufgrund leerer Beschreibung abgebrochen."
+	exit 1
+fi
 
 echo -n "Beginne mit dem Erstellen des Fehlerberichts..."
 
 . /opt/openslx/config
 
-echo "TIME INFORMATION:" > metadata
+echo "TIME INFORMATION (hwclock, date):" > metadata
 hwclock >> metadata
 date >> metadata
-for srv in 132.230.1.9 $SLX_NTP_SERVER 0.de.pool.ntp.org; do
-	ntpdate -u -q -p 2 -t 1 "$srv" >> metadata && break
+for srv in $SLX_NTP_SERVER 0.de.pool.ntp.org; do
+	ntpdate -u -q -p 2 -t 1 "$srv" >> metadata 2> /dev/null && break
 done
 echo -n "..."
 
 cp /opt/openslx/config /tmp/udhcpclog static/ 2> /dev/null
 echo -n "."
 
-find /tmp/vmware* -name "*.log" -exec cp {} static/ \; 2> /dev/null
+FILES=$(find /tmp/vmware* /tmp/virt /tmp/vmchooser* -type f \( -name "*.log" -o -name "*.conf" -o -name "*.xml" \) 2> /dev/null)
+if [ -n "$FILES" ]; then
+	tar ckf static/vm-related.tar $FILES
+fi
+
 echo -n "."
 
 cp /var/log/Xorg.0.lo* static/ 2> /dev/null
 cp /var/log/{auth.log,kdm.log,syslog,messages,user.log} static/ 2> /dev/null
-cp /proc/cpuinfo static/ 2> /dev/null
+cp /proc/{cpu,mem}info static/ 2> /dev/null
 echo -n "."
 
 for tool in $TOOLS; do
@@ -74,13 +88,15 @@ echo -n "."
 systemctl status > "generated/systemctl-status-out" 2> "generated/systemctl-status-err"
 echo -n "."
 
-ps aux > "generated/ps-out" 2> "generated/ps-err"
+ps auxf > "generated/ps-out" 2> "generated/ps-err"
 echo -n "."
+
+find generated/ -type f -name "*-err" -size 0 -delete > /dev/null 2>/dev/null
 
 echo "..fertig!"
 
 cd /tmp
-rm -f error-report.tar.gz
+rm -f -- error-report.tar.gz
 echo -n "Packe Fehlerbericht ein..."
 if ! tar czf error-report.tar.gz debug-report; then
 	echo "Fehler beim Packen des Berichts!" >&2
diff --git a/core/modules/run-virt/data/opt/openslx/scripts/systemd-mount_vm_store b/core/modules/run-virt/data/opt/openslx/scripts/systemd-mount_vm_store
--- a/core/modules/run-virt/data/opt/openslx/scripts/systemd-mount_vm_store
+++ b/core/modules/run-virt/data/opt/openslx/scripts/systemd-mount_vm_store
@@ -13,8 +13,12 @@ OUTFILE=$(mktemp)
 # no bash, so this is a bit ugly...
 if [ "${SLX_VM_NFS#//}" = "${SLX_VM_NFS}" ]; then
 	# doesn't start with '//' -> assume NFS
-	/opt/openslx/bin/timeout -t 10 -s 9 mount -v -t nfs -o ro,async,nolock "$SLX_VM_NFS" /mnt/vmstore
+	/opt/openslx/bin/timeout -t 6 -s 9 mount -v -t nfs -o ro,async,nolock "$SLX_VM_NFS" /mnt/vmstore
 	RET=$?
+	if [ "$RET" != "0" ]; then
+		/opt/openslx/bin/timeout -t 6 -s 9 mount -v -t nfs -o vers=3,ro,async,nolock "$SLX_VM_NFS" /mnt/vmstore
+		RET=$?
+	fi
 else
 	# starts with '//' -> assume CIFS
 	export USER="$SLX_VM_NFS_USER"
@@ -25,15 +29,14 @@ else
 	RET=$?
 fi > "$OUTFILE" 2>&1
 
-if [ $RET -ne 0 ]; then
+if [ "$RET" -ne "0" ]; then
 	if [ -s "$OUTFILE" ]; then
-		slxlog "mount-vmstore-fail" "Mounting '$SLX_VM_NFS' failed. VMs will not boot." "$OUTFILE"
-		sleep 1
+		slxlog --delete "mount-vmstore-fail" "Mounting '$SLX_VM_NFS' failed. VMs will not boot." "$OUTFILE"
 	else
 		slxlog "mount-vmstore-fail" "Mounting '$SLX_VM_NFS' failed. VMs will not boot."
+		rm -f -- "$OUTFILE"
 	fi
 fi
 
-rm -f -- "$OUTFILE"
 exit $RET
 
diff --git a/core/rootfs/rootfs-stage31/data/inc/activate_sysconfig b/core/rootfs/rootfs-stage31/data/inc/activate_sysconfig
--- a/core/rootfs/rootfs-stage31/data/inc/activate_sysconfig
+++ b/core/rootfs/rootfs-stage31/data/inc/activate_sysconfig
@@ -66,10 +66,15 @@ HEREEND
 	cd "${TEMP_EXTRACT_DIR}"
 	# first we look for local config.tgz files, which we merge with the common
 	# config.tgz files
-	local LOCAL_CONFIG_DIR="openslx-configs/${SLX_LOCAL_CONFIG}"
-	if [ -n "${SLX_LOCAL_CONFIG}" -a -d "${LOCAL_CONFIG_DIR}" ]; then
-		tarcopy "${LOCAL_CONFIG_DIR}" "${TEMP_EXTRACT_DIR}"
-		echo "Merged local configuration files for '${SLX_LOCAL_CONFIG}'"
+	if [ -n "${SLX_LOCAL_CONFIG}" ]; then
+		local MOD
+		for MOD in ${SLX_LOCAL_CONFIG}; do
+			local LOCAL_CONFIG_DIR="openslx-configs/${MOD}"
+			if [ -d "${LOCAL_CONFIG_DIR}" ]; then
+				tarcopy "${LOCAL_CONFIG_DIR}" "${TEMP_EXTRACT_DIR}"
+				echo "Merged local configuration files for '${MOD}'"
+			fi
+		done
 	fi
 	# purge openslx-configs/*
 	rm -rf -- "openslx-configs/"
@@ -91,6 +96,17 @@ HEREEND
 #
 
 fetch_sysconfig || drop_shell "Could not download remote config"
+if ! ash -n "${CONFIG}-remote"; then
+	echo -e "\n\tFATAL: Could not download configuration!"
+	echo -e "\tAborting boot since the system would be in an unusable state."
+	echo -en "\tRebooting in 60 seconds"
+	timeout=60
+	while [ $(( timeout-- )) -gt 0 ]; do
+		echo -n "."
+		sleep 1
+	done
+	echo b > /proc/sysrq-trigger
+fi
 . "${CONFIG}-remote" || drop_shell "Could not source remote config"
 fetch_config_files || drop_shell "Could not download config.tgz"
 update_sysconfig || drop_shell "Could not update sysconfig"
