[hardware-stats] Fix smartctl not reporting if HDD has issues

diff --git a/core/modules/hardware-stats/data/opt/openslx/scripts/systemd-hardware_stats b/core/modules/hardware-stats/data/opt/openslx/scripts/systemd-hardware_stats
--- a/core/modules/hardware-stats/data/opt/openslx/scripts/systemd-hardware_stats
+++ b/core/modules/hardware-stats/data/opt/openslx/scripts/systemd-hardware_stats
@@ -186,7 +186,10 @@ if which smartctl; then
 	[ -z "$FILE" ] && FILE="/tmp/smartctl.$$.$RANDOM.$RANDOM"
 	for dev in $(cat "$FDISK" | grep -o '^Disk /dev/\S*:' | cut -c 6-); do
 		dev=${dev:0:-1}
-		smartctl -i -H -A -f "brief" "$dev" > "$FILE" || continue
+		smartctl -i -H -A -f "brief" "$dev" > "$FILE"
+		# Exit code might be nonzero to indicate fail status, or because some (but not all) ATA commands
+		# failed. So instead, see if we at least got basic device information and go on if so.
+		grep -q -E -e '^Device Model:' -e '^\s*5\s.+\s.+\s.+\s[0-9]' "$FILE" || continue
 		echo "NEXTHDD=$dev" >> "$ALLSMART"
 		cat "$FILE" >> "$ALLSMART"
 		# parse
