[system-check/hardware-stats] Loosen dependencies
For some reason, system-check is ordered before hardware-report, but I
can't figure out why. system-check merely generates the warnings to
display on the login screen, and hardware-report sends hw data to the
boot server. I don't see anything in hardware-report actually depending
on anything system-check does.

There are some other minor changes, like moving the generation of the
json report from hardware-report to hardware-stats, and putting the
according python script into a directory named hardware-stats instead of
system-check, which might imply it belongs to that module which is wrong.

diff --git a/core/modules/hardware-stats/data/opt/openslx/scripts/systemd-hardware_report b/core/modules/hardware-stats/data/opt/openslx/scripts/systemd-hardware_report
--- a/core/modules/hardware-stats/data/opt/openslx/scripts/systemd-hardware_report
+++ b/core/modules/hardware-stats/data/opt/openslx/scripts/systemd-hardware_report
@@ -16,8 +16,9 @@ report_hardware_info() {
 		return 1
 	fi
 	hwreport="/run/hwreport"
-	if [ ! -s "$hwreport" ]; then
-		echo "Missing hwreport file: $hwreport"
+	jsonfile="/run/hwreport.json"
+	if ! [ -s "$hwreport" ] && ! [ -s "$jsonfile" ]; then
+		echo "Missing hwreport file: $hwreport AND $jsonfile"
 		# TODO send data without?
 		return 1
 	fi
@@ -50,14 +51,12 @@ report_hardware_info() {
 	# Get IP/subnet size
 	local primary="${SLX_BRIDGE:-br0}"
 	subnet="$( ip -o -f inet addr show "$primary" | awk '/scope global/ {print $4}' )"
-	# Finally, new json-based reporting
-	jsonfile="$( mktemp )"
-	if ! python3 /opt/openslx/system-check/collect_hw_info_json.py -p > "$jsonfile"; then
-		echo -n "" > "$jsonfile"
-	fi
+	# just assume the uuid/mac dumped are valid here (its checked often enough :))
+	[ -s "$hwreport" ] || touch "$hwreport"
+	[ -s "$jsonfile" ] || touch "$jsonfile"
+
 	# Bail out if a shutdown was triggered and submitted in the meantime
 	[ -e /run/openslx/shutdown.mutex ] && exit 0
-	# just assume the uuid/mac dumped are valid here (its checked often enough :))
 
 	# got everything, get the last infos
 	uptime=$(grep -oE '^[0-9]+' /proc/uptime)
