[idleaction] Fix shutdown after wakeup when cron tries to catch up

diff --git a/core/modules/idleaction/data/opt/openslx/scripts/idleaction-scheduled_action b/core/modules/idleaction/data/opt/openslx/scripts/idleaction-scheduled_action
--- a/core/modules/idleaction/data/opt/openslx/scripts/idleaction-scheduled_action
+++ b/core/modules/idleaction/data/opt/openslx/scripts/idleaction-scheduled_action
@@ -1,7 +1,7 @@
 #!/bin/ash
 
-if [ "$(whoami)" != "root" ]; then
-	echo "Only root can call this"
+if ! touch "/run"; then
+	echo "Only root can call this" >&2
 	exit 1
 fi
 
@@ -12,15 +12,43 @@ if [ "$1" = "--detach" ]; then
 fi
 
 if [ $# -lt 1 ]; then
-	echo "$0 [--detach] <reboot|poweroff> [delay_minutes]"
+	echo "$0 [--detach] <reboot|poweroff> [delay_minutes]" >&2
 	exit 2
 fi
 
+DELAY=
+TS=
 MODE=$1
-DELAY=$2
+shift
+
+while [ $# -gt 0 ]; do
+	if [ "$1" == "--time" ]; then
+		TS=$2
+		shift
+	elif [ "$1" == "--delay" ]; then
+		DELAY=$2
+		shift
+	else
+		break
+	fi
+	shift
+done
+[ -n "$1" ] && DELAY=$1
+
+if [ -n "$TS" ]; then
+	# Sanity check for trigger by cron
+	NOW=$(date +%s)
+	SHOULD=$(date -d "today $TS" +%s)
+	DIFF=$(( NOW - SHOULD ))
+	DIFF=${DIFF#-} # DIFF = Abs($DIFF)
+	if [ "$DIFF" -gt 90 ]; then
+		echo "Timestamp mismatch, ignoring request." >&2
+		exit 4
+	fi
+fi
 
 if [ "$MODE" != "reboot" ] && [ "$MODE" != "poweroff" ]; then
-	slxlog "idleaction-failed-call" "Invalid call to idleaction-scheduled_action. Mode '$MODE' unknown."
+	slxlog --echo "idleaction-failed-call" "Invalid call to idleaction-scheduled_action. Mode '$MODE' unknown." >&2
 	exit 3
 fi
 
