[rfs-stage32/vmware*] Change vmware version naming
Hard-coding the version check to VMware 12 and 15 isn't great for future
updates -- i.e. now, that VMware 16 is released. Instead make the
version check script return "new" or "legacy", and rename the targets:
vmware12 -> vmware-legacy
vmware15 -> vmware

The addon downloading/setup should then act upon this accordingly.

diff --git a/core/modules/vmware-version-check/data/opt/openslx/bin/vmware-get-supported-version b/core/modules/vmware-version-check/data/opt/openslx/bin/vmware-get-supported-version
--- a/core/modules/vmware-version-check/data/opt/openslx/bin/vmware-get-supported-version
+++ b/core/modules/vmware-version-check/data/opt/openslx/bin/vmware-get-supported-version
@@ -3,41 +3,30 @@
 # * Intel: check for "VMX Unrestricted Guest" CPU flag
 # * AMD:   check if CPU family is Bulldozer or newer
 
-VIRTTYPE=$(grep -m1 '^flags\s*:' /proc/cpuinfo | grep -wo -e svm -e vmx)
+VIRTTYPE="$( grep -m1 '^flags\s*:' /proc/cpuinfo | grep -woF -e svm -e vmx )"
 
 if [ -z "$VIRTTYPE" ]; then
-	echo 12
+	# No need to bother with msr
+	echo "legacy"
 	exit 0
 fi
 
 modprobe msr
 
-VT=
+version="legacy"
 if [ "$VIRTTYPE" = "vmx" ]; then    # intel
-	BIT1=$(rdmsr --bitfield 0:0 0x3a 2>/dev/null || echo "fail")
-	BIT2=$(rdmsr --bitfield 2:2 0x3a 2>/dev/null || echo "fail")
+	BIT1="$( rdmsr --bitfield 0:0 0x3a 2>/dev/null || echo "fail" )"
+	BIT2="$( rdmsr --bitfield 2:2 0x3a 2>/dev/null || echo "fail" )"
 	if [ "$BIT1" = "0" ] || [ "$BIT2" = "1" ]; then
-		VT="ENABLED"
+		flag="$( rdmsr --bitfield 5:5 0x485 )"
+		[ "$flag" = "1" ] && version="new"
 	fi
 elif [ "$VIRTTYPE" = "svm" ]; then  # amd
-	BIT=$(rdmsr --bitfield 4:4 0xc0010114 2>/dev/null || echo "fail")
+	BIT="$( rdmsr --bitfield 4:4 0xc0010114 2>/dev/null || echo "fail" )"
 	if [ "$BIT" = "0" ]; then
-		VT="ENABLED"
+		family="$( awk '$1$2 == "cpufamily" {print $NF;exit}' /proc/cpuinfo )"
+		[ "$family" -ge 21 ] && version="new"
 	fi
-fi
-
-if [ "$VT" != "ENABLED" ]; then
-	echo 12
-	exit 0
-fi
-
-version=12
-if [ "$VIRTTYPE" = "vmx" ]; then
-	flag="$( rdmsr --bitfield 5:5 0x485 )"
-	[ "$flag" = "1" ] && version=15
-elif [ "$VIRTTYPE" = "svm" ]; then
-	family="$( awk '$1$2 == "cpufamily" {print $NF;exit}' /proc/cpuinfo )"
-	[ "$family" -ge 21 ] && version=15
 fi
 
 echo "$version"
diff --git a/core/rootfs/rootfs-stage32/data/opt/openslx/scripts/systemd-download_slx_addons b/core/rootfs/rootfs-stage32/data/opt/openslx/scripts/systemd-download_slx_addons
--- a/core/rootfs/rootfs-stage32/data/opt/openslx/scripts/systemd-download_slx_addons
+++ b/core/rootfs/rootfs-stage32/data/opt/openslx/scripts/systemd-download_slx_addons
@@ -18,7 +18,7 @@
 . /opt/openslx/config || { echo "Could not source config!"; exit 23; }
 
 # source functions.inc for the download function
-. /opt/openslx/inc/functions || { echo "/opt/openslx/inc/functions not found!"; exit 1337; }
+. /opt/openslx/inc/functions || { echo "/opt/openslx/inc/functions not found!"; exit 42; }
 
 # quick fix for the missing FUTURE_ROOT needed by /opt/openslx/etc/functions.inc
 export FUTURE_ROOT="/"
@@ -65,13 +65,17 @@ if [ $# -eq 1 ]; then
 	FILE="$ADDON"
 	if [ "$ADDON" = "vmware" ]; then
 		# check with the helper
-		version="$(vmware-get-supported-version)"
-		FILE="vmware$version"
-		echo "Deciding to download $FILE instead of $ADDON after checking CPU"
+		version="$( vmware-get-supported-version )"
+		if [ "$version" = "legacy" ]; then
+			FILE="${ADDON}-${version}"
+		fi
+		echo "Deciding to download flavor '$version' of $ADDON ($FILE) after checking CPU"
 	fi
 	# XXX
 	if ! download "${SLX_BASE_PATH}/${FILE}.sqfs" "${ADDON_TARGET_PATH}"; then
-		slxlog --echo "addon-download" "Download of '${HTTP_BASE_PATH}/${ADDON}.sqfs' failed."
+		if [ "$ADDON" = "$FILE" ] || ! download "${SLX_BASE_PATH}/${ADDON}.sqfs" "${ADDON_TARGET_PATH}"; then
+			slxlog --echo "addon-download" "Download of '${HTTP_BASE_PATH}/${FILE}.sqfs' failed. (${ADDON})"
+		fi
 		exit 1
 	fi
 fi
